[build]
  base = "christmas-cracker-app"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"

# Next.js handles routing automatically, no redirects needed

[dev]
  command = "npm run dev"
  port = 3000
  publish = ".next"
